"""initial schema

Revision ID: 00259721c41e
Revises: 
Create Date: 2025-05-25 10:23:05.979833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00259721c41e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_user_username'), 'health_user', ['username'], unique=True)
    op.create_table('health_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['health_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timestamp', 'name', name='uq_healthdata_user_time_name')
    )
    op.create_table('health_active_energy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_apple_exercise_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_apple_stand_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_basal_energy_burned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_flights_climbed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_handwashing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_headphone_audio_exposure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_heart_rate',
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_heart_rate_variability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_physical_effort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_respiratory_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_resting_heart_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_six_minute_walking_test_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_sleep_analysis',
    sa.Column('core', sa.Float(), nullable=True),
    sa.Column('inBedStart', sa.DateTime(), nullable=True),
    sa.Column('inBed', sa.Float(), nullable=True),
    sa.Column('sleepStart', sa.DateTime(), nullable=True),
    sa.Column('rem', sa.Float(), nullable=True),
    sa.Column('sleepEnd', sa.DateTime(), nullable=True),
    sa.Column('inBedEnd', sa.DateTime(), nullable=True),
    sa.Column('awake', sa.Float(), nullable=True),
    sa.Column('asleep', sa.Float(), nullable=True),
    sa.Column('deep', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_stair_speed_down',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_vo2_max',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_walking_asymmetry_percentage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_walking_double_support_percentage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_walking_heart_rate_average',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_walking_running_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_walking_speed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    op.create_table('health_walking_step_length',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_data_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['health_data_id'], ['health_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('health_data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_walking_step_length')
    op.drop_table('health_walking_speed')
    op.drop_table('health_walking_running_distance')
    op.drop_table('health_walking_heart_rate_average')
    op.drop_table('health_walking_double_support_percentage')
    op.drop_table('health_walking_asymmetry_percentage')
    op.drop_table('health_vo2_max')
    op.drop_table('health_steps')
    op.drop_table('health_stair_speed_down')
    op.drop_table('health_sleep_analysis')
    op.drop_table('health_six_minute_walking_test_distance')
    op.drop_table('health_resting_heart_rate')
    op.drop_table('health_respiratory_rate')
    op.drop_table('health_physical_effort')
    op.drop_table('health_heart_rate_variability')
    op.drop_table('health_heart_rate')
    op.drop_table('health_headphone_audio_exposure')
    op.drop_table('health_handwashing')
    op.drop_table('health_flights_climbed')
    op.drop_table('health_basal_energy_burned')
    op.drop_table('health_apple_stand_time')
    op.drop_table('health_apple_exercise_time')
    op.drop_table('health_active_energy')
    op.drop_table('health_data')
    op.drop_index(op.f('ix_health_user_username'), table_name='health_user')
    op.drop_table('health_user')
    # ### end Alembic commands ###
