"""add location tracking table

Revision ID: 02cd3813355b
Revises: 0ff9ca20895b
Create Date: 2025-05-28 23:36:41.852997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02cd3813355b'
down_revision: Union[str, None] = '0ff9ca20895b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('acc', sa.Float(), nullable=True),
    sa.Column('batt', sa.Integer(), nullable=True),
    sa.Column('vel', sa.Float(), nullable=True),
    sa.Column('tid', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('last_weather_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_tracks')
    # ### end Alembic commands ###
