"""add weather alerts air quality marine and astronomy tables

Revision ID: 0ff9ca20895b
Revises: d428342dfae7
Create Date: 2025-05-28 22:58:42.447051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff9ca20895b'
down_revision: Union[str, None] = 'd428342dfae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('pm2_5', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('us_epa_index', sa.Integer(), nullable=True),
    sa.Column('gb_defra_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('astronomy_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('sunrise', sa.String(), nullable=True),
    sa.Column('sunset', sa.String(), nullable=True),
    sa.Column('moonrise', sa.String(), nullable=True),
    sa.Column('moonset', sa.String(), nullable=True),
    sa.Column('moon_phase', sa.String(), nullable=True),
    sa.Column('moon_illumination', sa.Integer(), nullable=True),
    sa.Column('is_moon_up', sa.Integer(), nullable=True),
    sa.Column('is_sun_up', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marine_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('tide_time', sa.String(), nullable=True),
    sa.Column('tide_height_mt', sa.Float(), nullable=True),
    sa.Column('tide_type', sa.String(), nullable=True),
    sa.Column('swell_height_m', sa.Float(), nullable=True),
    sa.Column('swell_direction', sa.String(), nullable=True),
    sa.Column('swell_direction_degrees', sa.Integer(), nullable=True),
    sa.Column('swell_period_seconds', sa.Integer(), nullable=True),
    sa.Column('water_temp_c', sa.Float(), nullable=True),
    sa.Column('water_temp_f', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('areas', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('certainty', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('effective', sa.String(), nullable=True),
    sa.Column('expires', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_alerts')
    op.drop_table('marine_weather')
    op.drop_table('astronomy_data')
    op.drop_table('air_quality')
    # ### end Alembic commands ###
