"""add weather information

Revision ID: d428342dfae7
Revises: e0316ff94f77
Create Date: 2025-05-28 22:28:16.458430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd428342dfae7'
down_revision: Union[str, None] = 'e0316ff94f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_region', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('last_updated_epoch', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('condition_text', sa.String(), nullable=True),
    sa.Column('condition_icon', sa.String(), nullable=True),
    sa.Column('condition_code', sa.Integer(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_degree', sa.Integer(), nullable=True),
    sa.Column('wind_dir', sa.String(), nullable=True),
    sa.Column('pressure_mb', sa.Integer(), nullable=True),
    sa.Column('pressure_in', sa.Integer(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('precip_in', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('cloud', sa.Integer(), nullable=True),
    sa.Column('feelslike_c', sa.Float(), nullable=True),
    sa.Column('feelslike_f', sa.Float(), nullable=True),
    sa.Column('windchill_c', sa.Float(), nullable=True),
    sa.Column('windchill_f', sa.Float(), nullable=True),
    sa.Column('heatindex_c', sa.Float(), nullable=True),
    sa.Column('heatindex_f', sa.Float(), nullable=True),
    sa.Column('dewpoint_c', sa.Float(), nullable=True),
    sa.Column('dewpoint_f', sa.Float(), nullable=True),
    sa.Column('vis_km', sa.Integer(), nullable=True),
    sa.Column('vis_miles', sa.Integer(), nullable=True),
    sa.Column('uv', sa.Integer(), nullable=True),
    sa.Column('gust_mph', sa.Float(), nullable=True),
    sa.Column('gust_kph', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    # ### end Alembic commands ###
