"""add detailed location information to location tracks

Revision ID: f9f96b796edc
Revises: 92aa91857dde
Create Date: 2025-05-30 21:47:49.187439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f96b796edc'
down_revision: Union[str, None] = '92aa91857dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_tracks', sa.Column('state_province', sa.String(), nullable=True))
    op.add_column('location_tracks', sa.Column('country', sa.String(), nullable=True))
    op.add_column('location_tracks', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('location_tracks', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('location_tracks', sa.Column('formatted_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_tracks', 'formatted_address')
    op.drop_column('location_tracks', 'postal_code')
    op.drop_column('location_tracks', 'country_code')
    op.drop_column('location_tracks', 'country')
    op.drop_column('location_tracks', 'state_province')
    # ### end Alembic commands ###
